SET GENERATOR CategoriasID TO 0;

INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 16 a 24',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 21 a 29',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 25 a 34',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 30 a 34',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 35 a 39',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 35 a 44',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 40 a 44',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 45 a 49',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 45 a 54',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 50 a 54',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 55 a 59',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Femeninos de 55 y más',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Kids 6A',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Kids 9 a 12',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Kids niña',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Kids niño',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 55 y más',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 16 a 24',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 21 a 29',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 25 a 34',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 30 a 34',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 35 a 39',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 35 a 44',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 40 a 44',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 45 a 49',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 45 a 54',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 50 a 54',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Masculinos de 55 a 59',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Hasta 15',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Hasta 20',1);
INSERT INTO Categorias (id, nombre, bVisible) VALUES (-1,'Hasta 24',1);

INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 1, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 2, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 3, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 4, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 5, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 6, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 7, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 8, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 9, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 10, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 11, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 12, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 13, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 14, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 15, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 16, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 17, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 18, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 19, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 20, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 21, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 22, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 23, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 24, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 25, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 26, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 27, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 28, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 29, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 30, 1);
INSERT INTO CategoriasCarrera (id, carrera_id, categoria_id, bVisible) VALUES (-1, '{0FEDD106-B4A3-2804-1974-C1C246BB1DF1}', 31, 1);

INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'25 de Mayo','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Allen','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Andacollo','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Av San Juan 1875','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Barda del Medio','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Bariloche','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Capital','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Catriel','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'CAVIAHUE','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Centenario','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Cervantes','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Chichinales','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Choele Choel','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Cinco Saltos','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Cipolletti','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'CLMTE CORDERO','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'CORONEL BELISLE','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Cutral Co','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'El Bolson','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'El Cholar','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'El Cuy','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Fernandez Oro','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'General Roca','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'ING. JACOBACCI','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'ING.HUERGO','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Las Lajas','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Luis Guillon','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'MAINQUE','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Mariano Moreno','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Moquehue','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Neuquen','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Piedra del Aguila','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Plaza Huincul','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Plottier','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Rio Negro','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Rio de los Sauces','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Rio Colorado','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'San Patricio del Chañar','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Sierra Colorada','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Villa El Chocon','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Villa Regina','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Villa Traful','',1);
INSERT INTO Localidades (id, localidad, codigoPostal, bVisible) VALUES (-1,'Zapala','',1);

SET GENERATOR TallesID TO 0;
INSERT INTO Talles (id, talle, bVisible) VALUES (-1, 'L', 1);
INSERT INTO Talles (id, talle, bVisible) VALUES (-1, 'M', 1);
INSERT INTO Talles (id, talle, bVisible) VALUES (-1, 'S', 1);
INSERT INTO Talles (id, talle, bVisible) VALUES (-1, 'XL', 1);
INSERT INTO Talles (id, talle, bVisible) VALUES (-1, 'XS', 1);
INSERT INTO Talles (id, talle, bVisible) VALUES (-1, 'XXL', 1);
INSERT INTO Talles (id, talle, bVisible) VALUES (-1, 'XXS', 1);
